### ISSUE TITLE
keras_tensorflowのノートブックにタイポ

### ISSUE THREAD

**Issue by rtaguchi** [harusametime/sagemaker-notebooks#1]
https://github.com/harusametime/sagemaker-notebooks/blob/master/keras_tensorflow/keras_tensorflow_mnist.ipynb

SageMakerのScript Modeを試す際に、上記のノートブックとソースコードを参考にさせて頂きました。ありがとうございます。
些細な点ですが検証中にタイポに気付いたので共有させて頂きます。

ノートブック中のTensorflowのEstimatorを呼び出す際に、ハイパーパラメータで「batch_size」「n_class」（アンダーバー）という項目を渡していますが、スクリプトファイルの方では「batch-size」「n-class」（ハイフン）というパラメータ名になっているため、ノートブックからパラメータが渡せていないのではないでしょうか。

**Comment by harusametime** [comment]
@rtaguchi ありがとうございます！おっしゃる通りで https://github.com/harusametime/sagemaker-notebooks/commit/5fc22c3b50b904d1403701a4cb2c7b4f5eb78551 でFixしました。
